<a href="https://colab.research.google.com/github/redrum88/pytorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.1503, 0.8765, 0.5667, 0.8593, 0.4163, 0.4424, 0.7329],
        [0.7011, 0.0268, 0.7152, 0.7979, 0.1247, 0.6937, 0.0292],
        [0.1915, 0.3778, 0.1689, 0.2108, 0.2338, 0.3662, 0.3123],
        [0.8709, 0.5963, 0.4756, 0.8554, 0.5013, 0.6141, 0.4055],
        [0.4942, 0.8287, 0.3356, 0.9693, 0.6770, 0.7374, 0.8063],
        [0.1692, 0.6615, 0.0898, 0.1622, 0.5950, 0.3704, 0.6523],
        [0.9472, 0.8634, 0.6768, 0.3324, 0.0236, 0.0381, 0.8367]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
another_random_tensor = torch.rand(1, 7)
# Perform matrix multiplication 
torch.mm(random_tensor, another_random_tensor.T)

tensor([[1.8042],
        [1.3663],
        [0.8536],
        [2.1036],
        [2.4258],
        [1.4184],
        [1.5729]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
SEED = 0

# Create two random tensors
torch.manual_seed(SEED)
random_tensor_1 = torch.rand(7, 7)

torch.manual_seed(SEED)
random_tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.manual_seed(SEED)
torch.mm(random_tensor_1, random_tensor_2.T), torch.mm(random_tensor_1, random_tensor_2.T).shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
torch.manual_seed(1234)
tensor_a = torch.rand(2, 3)
torch.manual_seed(1234)
tensor_b = torch.rand(2, 3)
tensor_a = tensor_a.to(device)
tensor_b = tensor_b.to(device)

tensor_a == tensor_b

Device: cuda


tensor([[True, True, True],
        [True, True, True]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
tensor_c = torch.mm(tensor_a, tensor_b.T)

### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
print(torch.max(tensor_c))

# Find min
print(torch.min(tensor_c))

tensor(0.6287, device='cuda:0')
tensor(0.2161, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [11]:
# Find arg max
print(torch.argmax(tensor_c))

# Find arg min
print(torch.argmin(tensor_c))

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
random_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(random_tensor_squeezed, random_tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
